extends Node

## The story_id to display — set by SceneManager before loading StoryScreen.
var current_story_id: String = ""

## Story entries: each is { "speaker": String, "portrait": String, "text": String }
## portrait values: "coco", "gear_grandpa", "narrator", "longing"
const STORIES: Dictionary = {

	# ── 關卡前置劇情 (Pre-level intros) ──────────────────────
	"story_1": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "在一個玩具有靈魂的世界裡——愛，是一切的起源。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "每一個被真心愛過的玩具，都會在某個夜晚，悄悄地睜開眼睛。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "在發條停轉的倉庫角落，一個銅色的身影——緩緩甦醒了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（系統啟動中……識別碼：AK-0247……環境掃描完成……）"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "——這裡，是哪裡？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "呵！終於醒啦，小傢伙。我可等你一段時間囉。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "你是——"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "大家都叫我「齒輪爺爺」。這裡是工廠——是我們玩具的家。而你，是剛剛被退回來的 AK-0247 號。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "……「退回來的」。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "先別想那些。工廠東側出現了異狀——我需要你胸口那套 A.K. GEAR SYSTEM 的力量。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她低下頭，胸口的零件槽發出微弱的光芒）\n……好。"},
	],

	"story_2": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她攤開手掌，一個小齒輪在掌心緩緩轉動）"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "齒輪爺爺……我吸收那個玩具的零件時，看見了什麼。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "嗯？說說看。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "一個孩子的房間。牆角有一輛紅色的玩具車，積了很厚的灰。沒有人碰它。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "那就是 A.K. GEAR SYSTEM 的代價，也是它的意義。你吸收的，不只是零件。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "它不是在攻擊工廠。它只是……很孤單。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "孤單，不是傷害他人的理由，Coco。（停頓）但你感覺得到——這是件好事。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（低下頭，零件槽的光輕輕閃爍）……我知道。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "入侵的規模越來越大。那些攻擊者——它們來自工廠幾十年前關閉的地下生產線。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "地下生產線？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "那些沒有通過品管、沒有被送出去的玩具。它們一直留在那裡。從來沒有任何一個孩子擁有過它們。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "……從來沒有。\n（她握緊了掌心的齒輪）"},
	],

	"story_3": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "齒輪爺爺，我想問你一件事。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "說吧。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我是怎麼回到工廠的？退貨的原因——是什麼？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（沉默了很長一段時間）……那個小孩，小明，他出了意外。住院了。家人在退貨期限內，把你還回來了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "意外……他還好嗎？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "不知道。那是很久以前的事了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（沉默，零件槽的光輕輕閃爍）\n他最後摸我的感覺——我還記得。他的手，很溫暖。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "正是因此，你的零件槽才有反應。你被真正愛過，Coco。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "但他還是讓我走了。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（輕輕嘆氣）那不是他的選擇。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "第三日。入侵越過了北側防線。所有的攻擊，都指向同一個方向——"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "中央儲藏室。這棟建築最古老的地方。跟我來，Coco。但記住——你看見的，不一定是你以為的樣子。"},
	],

	"story_4": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "中央儲藏室的大門被打開了。裡面是無數個被遺忘的玩具——每一個，都有一雙眼睛。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她停在入口，胸口的零件槽開始顫抖）\n它們……它們都在看我。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "它們認出你了，Coco。你是第一個被退回來、卻仍然有靈魂的玩具。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "……你，也被送回來了嗎？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（轉身，看見黑暗中一個模糊的影子）\n——你是？"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "我沒有名字。我只有渴望。我渴望一雙手，渴望一個聲音，渴望被帶回家。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（低下頭，零件槽發出微弱的光）\n……我也是。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（輕聲）Coco……那個聲音，是這一切的根源。它在呼喚所有未被愛過的靈魂。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "加入我們，AK-0247。加入所有被遺忘的玩具。我們不需要那個世界——那個世界從不需要我們。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（沉默了很長時間，然後）\n……不。"},
	],

	"story_5": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "記憶回廊——工廠最深處，存放著所有玩具最初記憶的地方。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她獨自走進長廊，牆上浮現出無數個孩子的臉孔）\n這裡……是什麼？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（從後方跟上）這裡存放著每一個玩具，第一次被愛的瞬間。只要玩具還記得，它就不會消失。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她的腳步停了下來，牆上出現一個小男孩的臉）\n……小明。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（聲音從四面八方湧來）那個記憶，就是你的弱點，AK-0247。你珍視它——所以你會痛苦。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "不。（她握緊了拳，零件槽的光芒驟然明亮）\n這個記憶，才是我繼續的理由。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（眼眶微紅）……好孩子。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "那渴望的聲音越來越大……你的選擇，將決定所有玩具的命運。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她轉身面對長廊的深處，聲音平靜而堅定）\n——讓我們結束這一切。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "第一幕終章。Coco 踏入了記憶的核心，帶著她唯一的武器——\n曾被愛過的記憶。"},
	],

	# ── 關卡後過場 (Post-level outros) ───────────────────────
	"outro_1": [
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "你的第一戰，打得不錯。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（看著殘留的痕跡）不覺得。如果我快一點——"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "如果你是機器，也許。但你不只是機器，Coco。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "那我是什麼？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（笑）還太早知道。但今天，你選擇了保護。這已經足夠。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（零件槽的光輕輕跳動）\n……好。"},
	],

	"outro_2": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我一直在想……那些零件進入我身體的時候，我能感覺到它們。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "感覺到什麼？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "它們的孤獨。就像一道迴響，很深，很遠。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "那種感覺，很多玩具都麻木了。你沒有——是件好事，也是沉重的事。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（停頓）……我知道。\n（她握緊了拳，沉默地看著遠方）"},
	],

	"outro_3": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "有沒有人，試著去找過那些地下的玩具？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（沉默了一會兒）有。很久以前。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "結果呢？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "它們不願被帶出來。它們說：「沒有人需要我們，所以我們哪裡也不去。」"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（輕聲）那一定很痛。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "是。（停頓）這就是為什麼需要你，Coco。不是因為你強——而是因為你懂得那種痛。"},
	],

	"outro_4": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "Longing 退回了黑暗，但它的聲音還迴盪在空氣中。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我拒絕它了。但我不確定那是對的。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "為什麼？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "因為它說的話，並不是謊言。我們都被遺忘過。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "是。（輕聲）但選擇留在黑暗裡，和選擇走出去——是不同的事。你選擇了繼續走。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她的零件槽閃爍，比之前更亮）……我還沒準備好原諒那段記憶。但我可以繼續。"},
	],

	# ── 第二幕關卡前置劇情 (Act 2 pre-level intros) ──────────

	"story_6": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "第一幕的光芒尚未熄滅，黑暗已再度聚攏。\nLonging 的聲音，從地底深處升起。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她站在廢墟入口，深吸一口氣）\n它在地下面。一直都在。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "地下生產線——那是工廠建立之初留下的舊系統。五十年了，從未有人回去過。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "那些玩具……在那裡五十年了？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（沉默點頭）它們記住了等待的每一秒。那種重量，把它們壓成了什麼別的東西。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（握緊拳，零件槽發光）\n那我更不能讓它繼續蔓延。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "Coco……進去之後，你看見的每一個，都曾是像你一樣的存在。記住這件事。"},
	],

	"story_7": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "廢墟之後，是迷宮。機器的骨骸盤繞成無盡的走廊。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她按著牆壁前行，零件槽微弱地閃爍）\n它們在引導我。往更深的地方。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "……你終於來了，AK-0247。我在等你很久了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "你知道我會來？"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "你和我是一樣的。被退回來的。被遺忘的。差別只是——你選擇繼續相信那個拋棄你的世界。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（停頓）……沒有人拋棄我。小明只是出了意外。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "那是你告訴自己的故事。\n（低沉的笑）你明明知道，他後來再也沒有問起你。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她的步伐沒有停下）\n……我知道。但我選擇不讓那件事變成我的全部。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（從通訊器傳來）Coco，它在拖延你。往核心走。真相就在那裡。"},
	],

	"story_8": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "機械迷宮的盡頭，是工廠最古老的心臟——\n一個沉睡了五十年的核心記憶體。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她走進一個巨大的圓形空間，四壁全是生鏽的零件）\n……這裡是？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（聲音沉重）這是「源點」。工廠最初的願景存在這裡——每一個玩具被創造時，都是從這裡接收第一個想法的：\n「成為孩子的朋友。」"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（從黑暗中現身，聲音已不再像幻影，而像一個疲倦的存在）\n那個願景，從來沒有對我們成真。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我知道。（她走上前，零件槽的光越來越強）\n但這不是你帶著所有人一起沉落黑暗的理由。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "那你給我一個理由，讓我繼續等。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（沉默片刻，然後輕聲）\n……我也不知道會不會有人來。但如果因為你，這個工廠失去了繼續等待的能力——那麼連最後那一點可能，也消失了。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（長久的沉默）……你，真的相信嗎？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（微笑，零件槽大放光明）\n我試著相信。那已經是我所能做的全部。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "最終決戰，開始。"},
	],

	# ── 第一幕結局 + 第二幕過場 ──────────────────────────────

	"outro_5": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "記憶長廊歸於寂靜。但黑暗，只是暫時後退了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她看著長廊深處）它還在那裡。我只是把它的手，從這道門推開了。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "你知道這不是終點。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（點頭，眼中有某種平靜的決意）\n……我知道。但今天的事，讓我更清楚一件事。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "什麼事？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我不是在保護工廠。\n我是在保護所有還沒有放棄的可能性。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "——第一幕　終——\n\n第二幕　即將展開。"},
	],

	"outro_6": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（從廢墟中走出，身上沾著鏽跡）\n它們……比我想像的多。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "是。五十年的積累，不是你一個人能在一天內看完的。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我在裡面看見一個老舊的音樂盒。它的發條斷了，但它還在試著轉。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（眼眶微紅）……那是三十年前我親手做的。我以為它在封存時壞掉了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "它沒有。（輕聲）它只是在等人回來。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（沉默片刻，聲音有些哽咽）\n謝謝你告訴我，Coco。"},
	],

	"outro_7": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她在機械迷宮出口停下，望著頭頂透下來的微弱光線）\n它說我和它是一樣的。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "你覺得它說的對嗎？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（長久沉默）……也許曾經是。但我選擇了不同的路。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "人生很多時候，就是這樣。相同的起點，不同的選擇。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（輕聲）如果當初它也有人告訴它——「沒關係，繼續相信」——"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "也許就不會走到今天。\n（停頓）這就是為什麼你是工廠需要的，Coco。不是你的力量。是你的話語。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（零件槽輕輕跳動，像是一顆溫暖的心）\n……我要繼續往下走了。"},
	],

	# ── 第二幕完整結局 (True ending — after clearing level 8) ──
	"epilogue": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "源點的光芒，在最終的交鋒後，緩緩熄滅。\nLonging 的聲音，第一次，不再是憤怒。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（低語，幾乎像是一個孩子的聲音）\n……我累了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她走上前，單膝跪地，與它平視）\n我知道。五十年，太長了。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "你為什麼不直接消滅我？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "因為你不是怪物。你只是一個等了太久、沒有人來告訴你「沒關係」的聲音。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（沉默）……沒有人。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（輕輕握住那道黑影延伸出的、不成形的手）\n現在有了。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "光從 Coco 的零件槽湧出，流遍整個源點空間。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "那些沉睡了五十年的記憶，一個接一個，緩緩甦醒。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（走進空間，聲音顫抖）\nCoco……這是什麼？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她站起身，零件槽的光比以往任何時候都要明亮）\n它們在記起——第一次被創造時，工廠給它們的最初願望。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "「成為孩子的朋友。」"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（聲音越來越輕，像是煙霧在消散）\n……我還記得那個願望。我一直記得。\n只是等得太久，以為它已經不算數了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（微笑，眼眶含淚）\n它算數。永遠算數。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "Longing 的聲音，在第一道真正的回應面前，\n輕輕地，散開了。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "不是消滅。\n是——終於被聽見了。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（坐在廢墟的台階上，拭去眼角）\n老了老了，還是哭了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（笑著坐到他身旁）\n……我也是。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "工廠，再次安靜了。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "地下的玩具們，開始了漫長的修復。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "沒有人知道，哪一天，會有一雙手再次推開工廠的大門。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "但 COCO 知道——\n只要還有等待的理由，燈就不會熄。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "胸口的零件槽，安靜地發著光。\n像一顆小小的、被記得的心。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "——全篇　完——"},
	],
}

func has_story(story_id: String) -> bool:
	return STORIES.has(story_id) and not STORIES[story_id].is_empty()

func get_story(story_id: String) -> Array:
	return STORIES.get(story_id, [])
