extends Node

## The story_id to display — set by SceneManager before loading StoryScreen.
var current_story_id: String = ""

## Story entries: each is { "speaker": String, "portrait": String, "text": String }
## portrait values: "coco", "gear_grandpa", "narrator", "longing"
const STORIES: Dictionary = {
	"story_1": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "在一個玩具有靈魂的世界裡——愛，是一切的起源。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "每一個被真心愛過的玩具，都會在某個夜晚，悄悄地睜開眼睛。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "在發條停轉的倉庫角落，一個銅色的身影——緩緩甦醒了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（系統啟動中……識別碼：AK-0247……環境掃描完成……）"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "——這裡，是哪裡？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "呵！終於醒啦，小傢伙。我可等你一段時間囉。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "你是——"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "大家都叫我「齒輪爺爺」。這裡是工廠——是我們玩具的家。而你，是剛剛被退回來的 AK-0247 號。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "……「退回來的」。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "先別想那些。工廠東側出現了異狀——我需要你胸口那套 A.K. GEAR SYSTEM 的力量。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她低下頭，胸口的零件槽發出微弱的光芒）\n……好。"},
	],
	"story_2": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她攤開手掌，一個小齒輪在掌心緩緩轉動）"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "齒輪爺爺……我吸收那個玩具的零件時，看見了什麼。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "嗯？說說看。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "一個孩子的房間。牆角有一輛紅色的玩具車，積了很厚的灰。沒有人碰它。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "那就是 A.K. GEAR SYSTEM 的代價，也是它的意義。你吸收的，不只是零件。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "它不是在攻擊工廠。它只是……很孤單。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "孤單，不是傷害他人的理由，Coco。（停頓）但你感覺得到——這是件好事。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（低下頭，零件槽的光輕輕閃爍）……我知道。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "入侵的規模越來越大。那些攻擊者——它們來自工廠幾十年前關閉的地下生產線。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "地下生產線？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "那些沒有通過品管、沒有被送出去的玩具。它們一直留在那裡。從來沒有任何一個孩子擁有過它們。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "……從來沒有。\n（她握緊了掌心的齒輪）"},
	],
	"story_3": [
		{"speaker": "COCO", "portrait": "coco",
		 "text": "齒輪爺爺，我想問你一件事。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "說吧。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "我是怎麼回到工廠的？退貨的原因——是什麼？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（沉默了很長一段時間）……那個小孩，小明，他出了意外。住院了。家人在退貨期限內，把你還回來了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "意外……他還好嗎？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "不知道。那是很久以前的事了。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（沉默，零件槽的光輕輕閃爍）\n他最後摸我的感覺——我還記得。他的手，很溫暖。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "正是因此，你的零件槽才有反應。你被真正愛過，Coco。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "但他還是讓我走了。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（輕輕嘆氣）那不是他的選擇。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "第三日。入侵越過了北側防線。所有的攻擊，都指向同一個方向——"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "中央儲藏室。這棟建築最古老的地方。跟我來，Coco。但記住——你看見的，不一定是你以為的樣子。"},
	],
	"story_4": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "中央儲藏室的大門被打開了。裡面是無數個被遺忘的玩具——每一個，都有一雙眼睛。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她停在入口，胸口的零件槽開始顫抖）\n它們……它們都在看我。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "它們認出你了，Coco。你是第一個被退回來、卻仍然有靈魂的玩具。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "……你，也被送回來了嗎？"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（轉身，看見黑暗中一個模糊的影子）\n——你是？"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "我沒有名字。我只有渴望。我渴望一雙手，渴望一個聲音，渴望被帶回家。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（低下頭，零件槽發出微弱的光）\n……我也是。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（輕聲）Coco……那個聲音，是這一切的根源。它在呼喚所有未被愛過的靈魂。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "加入我們，AK-0247。加入所有被遺忘的玩具。我們不需要那個世界——那個世界從不需要我們。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（沉默了很長時間，然後）\n……不。"},
	],
	"story_5": [
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "記憶回廊——工廠最深處，存放著所有玩具最初記憶的地方。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她獨自走進長廊，牆上浮現出無數個孩子的臉孔）\n這裡……是什麼？"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（從後方跟上）這裡存放著每一個玩具，第一次被愛的瞬間。只要玩具還記得，它就不會消失。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她的腳步停了下來，牆上出現一個小男孩的臉）\n……小明。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "（聲音從四面八方湧來）那個記憶，就是你的弱點，AK-0247。你珍視它——所以你會痛苦。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "不。（她握緊了拳，零件槽的光芒驟然明亮）\n這個記憶，才是我繼續的理由。"},
		{"speaker": "齒輪爺爺", "portrait": "gear_grandpa",
		 "text": "（眼眶微紅）……好孩子。"},
		{"speaker": "Longing", "portrait": "longing",
		 "text": "那渴望的聲音越來越大……你的選擇，將決定所有玩具的命運。"},
		{"speaker": "COCO", "portrait": "coco",
		 "text": "（她轉身面對長廊的深處，聲音平靜而堅定）\n——讓我們結束這一切。"},
		{"speaker": "旁白", "portrait": "narrator",
		 "text": "第一幕終章。Coco 踏入了記憶的核心，帶著她唯一的武器——\n曾被愛過的記憶。"},
	],
}

func has_story(story_id: String) -> bool:
	return STORIES.has(story_id) and not STORIES[story_id].is_empty()

func get_story(story_id: String) -> Array:
	return STORIES.get(story_id, [])
